Basics/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,

)

# router = routers.DefaultRouter()
# router.register('postapi', views.PostSerializeView)

urlpatterns = [
    path('', PostListView.as_view(), name='Basics-home'),
    path('user/<str:full_name>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('about/', views.about, name='Basics-about'),
    path('chart/', views.display_chart, name='Basics-chart'),
    path('chart_general/', views.display_chart_general, name='Basics-chart-general'),
    path('chart_line/', views.display_chart_line, name='Basics-chart-line'),
    path('results/', views.result, name='Basics-results'),
    path('result/pdf/<str:term>/', views.generate_pdf, name='pdf'),
    path('students-results/', views.students_result, name='Basics-student-results'),
    path('post/new/ajax/', views.load_subjects, name='ajax-load-subject'),
    # path('api/', include(router.urls))
]

ResultSight/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('Basics.urls')),
    # path('Register/', user_views.register, name = 'register'),
    path('register/', include('users.urls')),
    path('', include('Basics.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='users-login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='users-logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name = 'users/password_reset.html'), name = 'password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'users/password_reset_done.html'), name = 'password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('profile/', user_views.profile, name='users-profile'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from .views import StudentSignUpView, TeacherSignUpView

urlpatterns = [
    path('', views.register, name='users-register'),
    path('student/', StudentSignUpView.as_view(), name='users-student'),
    path('teacher/', TeacherSignUpView.as_view(), name='users-teacher'),
    path('teacher/ajax', views.load_subjects, name='ajax-load-subjects')

]

Basics/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse
from users.models import UserStudent, Subject, ExamTitle

User = get_user_model()


# Create your models here.
class Post(models.Model):
    title = models.ForeignKey(ExamTitle, on_delete=models.PROTECT, blank=False)
    teacher = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title.name

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class Marks(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    student = models.ForeignKey(UserStudent, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    marks_obtained = models.IntegerField()

    def __str__(self):
        return self.subject.name


class Result(models.Model):
    title = models.CharField(max_length=30)
    student = models.OneToOneField(UserStudent, on_delete=models.CASCADE)
    remarks = models.CharField(max_length=10, default='Pass')
    division = models.FloatField(max_length=10, default=30.0)
    grand_total = models.IntegerField(default=0)

    def __str__(self):
        return self.title

Basics/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Post, Result
from users.models import Course, Semester, Subject, UserTeacher, UserStudent, Batch


class PostForm(forms.ModelForm):
    course = forms.ModelChoiceField(
        queryset=Course.objects.all()
    )
    semester = forms.ModelChoiceField(
        queryset=Semester.objects.all()
    )
    subject = forms.ModelChoiceField(
        queryset=Subject.objects.all()
    )

    batch = forms.ModelChoiceField(
        queryset=Batch.objects.all()
    )

    class Meta:
        model = Post
        fields = ['title', 'description', 'course', 'batch', 'semester', 'subject', ]

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        teacher_id = self.user.userteacher.id
        self.fields['course'].queryset = Course.objects.filter(userteacher=teacher_id)
        self.fields['semester'].queryset = Semester.objects.filter(userteacher=teacher_id)
        self.fields['batch'].queryset = Batch.objects.filter()


# class ResultForm(forms.ModelForm):
#     course = forms.ModelChoiceField(
#         queryset=Course.objects.all()
#     )
#     semester = forms.ModelChoiceField(
#         queryset=Semester.objects.all()
#     )
#     subject = forms.ModelMultipleChoiceField(
#         queryset=Subject.objects.all(), widget=forms.CheckboxSelectMultiple
#     )
#
#     class Meta:
#         model = Marks
#         fields = ['semester', 'course', 'subject', 'student', 'marks_obtained', ]
#
#     def __init__(self, *args, **kwargs):
#         self.user = kwargs.pop('user')
#         super().__init__(*args, **kwargs)
#         teacher_id = self.user.userteacher.id
#         courses = Course.objects.filter(userteacher=teacher_id)
#         semesters = Semester.objects.filter(userteacher=teacher_id)
#         print(teacher_id)
#         self.fields['course'].queryset = courses
#         self.fields['semester'].queryset = semesters
        # self.fields['subject'].queryset = Subject.objects.filter(teacher=teacher_id)
        # self.fields['student'].queryset = UserStudent.objects.filter(teacher_id=teacher_id))
        # counts = UserStudent.objects.filter(course_id=course).filter(semester_id=semester).count()

        # if my_list:
        #     self.fields['course'].queryset = my_list[1]
        #     self.fields['semester'].queryset = my_list[0]
        #     self.fields['subject'].queryset = my_list[2]

    # def clean(self):
    #     cleaned_data = super(ResultForm, self).clean()
    #     course = cleaned_data.get('course')
    #     semester = cleaned_data.get('semester')
    #     subject = cleaned_data.get('subject')
    #     print(course)
    #     print(subject)
    #     print(semester)


class ReportForm(forms.ModelForm):
    course = forms.ModelChoiceField(
        queryset=Course.objects.all()
    )
    semester = forms.ModelChoiceField(
        queryset=Semester.objects.all()
    )
    subject = forms.ModelChoiceField(
        queryset=Subject.objects.all()
    )

    class Meta:
        model = Result
        fields = ['course', 'semester', 'student', 'remarks', 'division', 'title', ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        course = self.data.get('course')
        # print("Course_id" + str(course))
        semester = self.data.get('semester')
        # print("semester_id" + str(semester))
        subject = self.data.get('subject')
        # print("Subject_id" + str(subject))
        # self.fields['subject'].queryset = Subject.objects.filter(id=subject)
        self.fields['course'].queryset = Course.objects.filter(id=course)
        self.fields['semester'].queryset = Semester.objects.filter(id=semester)
        self.fields['student'].queryset = UserStudent.objects.filter(course_id=course).filter(semester_id=semester)



Basics/templates/Basics/about.html
{% extends "Basics/base.html" %}

{% block content %}
 <div class="container">
	    <p>This website is called ResultSIght.</p>
        <p> We can create the results of students and</p>
		<p>students can view their respective result and</p>
		<p> keep tracks of their reuslt in the most easitest</p>
		<p> and convinient way.</p>
		<p>Hello Srijal, added this through webhook</p>

		<p>Assignment by Idea Breed.</p>
 </div>
{% endblock content %}

Basics/templates/Basics/display_chart.html
{% extends "Basics/base.html" %}
{#<script src="http://yui.yahooapis.com/3.10.0/build/yui/yui-min.js"></script>#}


{% block script %}
    <script>
    $(document).ready(function () {
        var ctx = document.getElementById('myChart').getContext('2d');
        charts = [];
{#        {% for semester, terms in result.items %}#}
{#        {% for term, results in terms.items %}#}
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [
                    {% for semester, terms in result.items %}
                        {% for term, results in terms.items %}
                            {% for item in results.marks %}
                                "{{ item.0 }}({{ term }})",
                            {% endfor %}
                        {% endfor %}
                    {% endfor %}
                ],
                datasets: [{
                    label: 'Marks obtained',
                    data: [
                        {% for semester, terms in result.items %}
                            {% for term, results in terms.items %}
                                {% for item in results.marks %}
                                    "{{ item.3 }}",
                                {% endfor %}
                            {% endfor %}
                        {% endfor %}
                    ],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
{#        {% endfor %}#}
{#        {% endfor %}#}
        })
    </script>
{% endblock script %}

{% block content %}

<canvas id="myChart" width="200" height="200"></canvas>

{% endblock content %}

Basics/templates/Basics/display_chart_line_chart.html
{% extends "Basics/base.html" %}
{#<script src="http://yui.yahooapis.com/3.10.0/build/yui/yui-min.js"></script>#}


{% block script %}
    <a class="btn btn-secondary btn-sm" href="{% url 'Basics-chart-general' %}"> Bar Chart</a>
    <script>
    $(document).ready(function () {
        var ctx = document.getElementById('myChart').getContext('2d');
        charts = [];
{#        {% for semester, terms in result.items %}#}
{#        {% for term, results in terms.items %}#}
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [
                    {% for semester, terms in result.items %}
                        {% for term, results in terms.items %}
                                "{{term }}%",
                        {% endfor %}
                    {% endfor %}
                ],
                datasets: [{
                    label: 'Percentage',
                    data: [
                        {% for semester, terms in result.items %}
                            {% for term, results in terms.items %}
                                    "{{ results.total.percentage }}",
                            {% endfor %}
                        {% endfor %}
                    ],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
{#        {% endfor %}#}
{#        {% endfor %}#}
        })
    </script>
{% endblock script %}

{% block content %}

<canvas id="myChart" width="200" height="200"></canvas>

{% endblock content %}

Basics/templates/Basics/dropdown_subject.html
{#<option value="">---------</option>#}

<select name="subject" class="select form-control">
{% for subject in subjects %}
        <option value="{{subject.id }}" >{{subject.name }} </option>
{% endfor %}
</select>
<br/>
<div>
    <label for="marks">Marks</label>
<table>
    <tr>
        <th>Name</th>
        <th>Marks Obtained</th>
    </tr>
    {% for student in students %}
        <tr>
        <td>{{ student.user__full_name }}</td>
        <td><input type="hidden" name="students[]" value="{{ student.id }}">
            <input type="number" class="form-control" name="marks[]" min="0" max="100"></td>
        </tr>
    {% endfor %}
</table>
</div>

Basics/templates/Basics/dsplay_chart_general.html
{% extends "Basics/base.html" %}
{#<script src="http://yui.yahooapis.com/3.10.0/build/yui/yui-min.js"></script>#}


{% block script %}
    <a class="btn btn-secondary btn-sm" href="{% url 'Basics-chart-line' %}"> Line Chart</a>
    <script>
    $(document).ready(function () {
        var ctx = document.getElementById('myChart').getContext('2d');
        charts = [];
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [
                    {% for semester, terms in result.items %}
                        {% for term, results in terms.items %}
                                "{{term }}%",
                        {% endfor %}
                    {% endfor %}
                ],
                datasets: [{
                    label: 'Percentage',
                    data: [
                        {% for semester, terms in result.items %}
                            {% for term, results in terms.items %}
                                    "{{ results.total.percentage }}",
                            {% endfor %}
                        {% endfor %}
                    ],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                         'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                         'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',

                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
{#        {% endfor %}#}
{#        {% endfor %}#}
        })
    </script>
{% endblock script %}

{% block content %}

<canvas id="myChart" width="200" height="200"></canvas>

{% endblock content %}

Basics/templates/Basics/home.html
{% extends "Basics/base.html" %}
{% block content %}
        {% for post in post %}
			<article class="media content-section">
			<img class = "rounded-circle article-img" src="{{ post.teacher.profile.image.url }}">
				  <div class="media-body">
					    <div class="article-metadata">
					      <a class="mr-2" href="{% url 'user-posts'  post.teacher.full_name %}">{{ post.teacher }}</a>
					      <small class="text-muted">{{ post.date_posted|date:"F d, Y " }}</small>
					    </div>
					    <h2><a class="article-title" href="{% url 'post-detail' post.id %}" >{{ post.title }}</a></h2>
                      <h6>{{ post.description }}</h6>
					    <p class="article-content">{{ post.content }}</p>
				  </div>
			</article>
		{% endfor %}

		{% if is_paginated %}
			{% if page_obj.has_previous %}
				<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
				<a class ="btn btn-outline-info mb-4" href= "?page={{ page_obj.previous_page_number }} ">Previous</a>
			{% endif %}

			{% for num in page_obj.paginator.page_range %}
				{% if page_obj.number == num %}
					<a class= "btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
				{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'+3' %}
					<a class= "btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
				{% endif %}
			{% endfor %}

			{% if page_obj.has_next %}
				<a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
				<a class ="btn btn-outline-info mb-4" href= "?page={{ page_obj.paginator.num_pages}} ">Last</a>
			{% endif %}

		{% endif %}
{% endblock content %}

Basics/templates/Basics/post_confirm_delete.html
{% extends 'Basics/base.html' %}

	{% block content %}
		<div class="content-section">
			<form method = "POST">
				{% csrf_token %}
					<fieldset class="form-group">
						<legend class="border-bottom mb-4">
							Delete Post
						</legend>
						<h2>Are you sure you want to delete the Post {{ object.title }}</h2>
					</fieldset>
					<diiv class="form-group">
						<button class="btn btn-outline-danger" type="submit">
							Yes, Delete
						</button>
						<a class="btn btn-outline-secondary" href = "{% url 'post-detail' object.id %}">
							Cancel
						</a>
					</diiv>
			</form>
		</div>

	{% endblock content %}

Basics/templates/Basics/result_form.html
{#{% extends 'Basics/base.html' %}#}
{#{% load crispy_forms_tags %}#}
{##}
{#	{% block content %}#}
{#        <form method="post">#}
{#            {% csrf_token %}#}
{#            {{ form|crispy }}#}
{#        </form>#}
{#        <form  method='post'>#}
{#        {% csrf_token %}#}
{#            <fieldset class="form-group">#}
{#                <legend class="border-bottom mb-4">#}
{#                    Create Result#}
{#                </legend>#}
{##}
{#                <div id="div_id_semester" class="form-group">#}
{#                    <label for="id_semester" class=" requiredField">Semester<span class="asteriskField">*</span></label>#}
{#                    <div class="">#}
{#                        <select name="semester" class="select form-control" required id="id_semester">#}
{#                            <option value="">{{my_dict.semester}}</option>#}
{#                        </select>#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div id="div_id_subject" class="form-group">#}
{#                    <label for="<id_sub></id_sub>ject" class=" requiredField"> Subject<span class="asteriskField">*</span></label>#}
{#                    <div class="">#}
{#                        <select name="subject" class="select form-control" required id="id_subject">#}
{#                            <option value="">{{my_dict.subject}}</option>#}
{#                        </select>#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div id="div_id_course" class="form-group">#}
{#                    <label for="id_course" class=" requiredField">Course<span class="asteriskField">*</span> </label>#}
{#                <div class="">#}
{#                    <select name="course" class="select form-control" required id="id_course">#}
{#                        <option value="">{{my_dict.course}}</option>#}
{#                    </select>#}
{#                </div>#}
{#                </div>#}
{#                {% for c in students%}#}
{#                    <div class="row">#}
{#                    <div id="div_id_student" class="col-md-6">#}
{#                        <label for="id_student" class=" requiredField">Student<span class="asteriskField">*</span> </label>#}
{#                        <div class="">#}
{#                            <select name="student" class="select form-control is-invalid" required id="id_student">#}
{#                                <option value="" selected>{{c}}</option>#}
{#                            </select>#}
{#                            <p id="error_1_id_student" class="invalid-feedback"><strong>This field is required.</strong></p>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div id="div_id_marks_obtained" class="col-md-6">#}
{#                        <label for="id_marks_obtained" class=" requiredField">Marks obtained<span class="asteriskField">*</span> </label>#}
{#                        <div class="">#}
{#                            <input type="number" name="marks_obtained" class="numberinput form-control is-invalid" required id="id_marks_obtained">#}
{#                            <p id="error_1_id_marks_obtained" class="invalid-feedback"><strong>This field is required.</strong></p>#}
{#                        </div>#}
{#                    </div>#}
{#                    </div>#}
{#                {% endfor %}#}
{##}
{##}
{##}
{##}
{#  {{ form.non_field_errors }}#}
{#  {{ form.source.errors }}#}
{#  {{ form.source }}#}
{##}
{##}
{##}
{#        <div>#}
{#          <label>{{ form.subject.label_tag }}</label>#}
{##}
{#          {{ form.subject.errors }}#}
{#          {{ form.subject }}#}
{##}
{#        </div>#}
{##}
{#        <div>#}
{#            {{ form.semester.label_tag }}#}
{#            {{ form.semester.errors }}#}
{#            {{ form.semester }}#}
{#        </div>#}
{##}
{##}
{#        <div>#}
{#            {{ form.course.label_tag }}#}
{#            {{ form.course.errors }}#}
{#            {{ form.course }}#}
{#            {{ form.course.help_text }}#}
{#        </div>#}
{##}
{#        <div>#}
{#            {% for c in students%}#}
{#              <div class="row">#}
{#                    {{ form.student.label_tag }}#}
{#                    {{ form.student.errors }}#}
{#                    {{ form.student }}#}
{#                    {{ form.student.help_text }}#}
{##}
{##}
{#                    {{ form.marks_obtained.label_tag }}#}
{#                    {{ form.marks_otained.errors }}#}
{#                    {{ form.marks_obtained}}#}
{#                    {{ form.marks_obtained.help_text }}#}
{##}
{#              </div>#}
{#            {% endfor %}#}
{#        </div>#}
{##}
{##}
{##}
{##}
{##}
{##}
{##}
{#            </fieldset>#}
{#            <div class="form-group">#}
{#                <button class="btn btn-outline-dark" type="submit">#}
{#                    Save Marks#}
{#                </button>#}
{#            </div>#}
{#        </form>#}
{##}
{#	{% endblock content %}#}

Basics/templates/Basics/student_results.html
{% extends 'Basics/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
{#  <form class="form-inline" method="GET" action="">#}
{#      <div class="form-group mx-sm-3 mb-2">#}
{#        <label for="inputPassword2" class="sr-only">Password</label>#}
{#        <input type="text" class="form-control" id="inputPassword2" placeholder="Course">#}
{#      </div>#}
{#      <div class="form-group mx-sm-3 mb-2">#}
{#        <label for="inputPassword2" class="sr-only">Password</label>#}
{#        <input type="text" class="form-control" id="inputPassword2" placeholder="Semester">#}
{#      </div>#}
{#    <button type="submit" class="btn btn-info mb-2">Search Result</button>#}
{#    </form>#}


    {% for semester, terms in result.items %}
      {% for term, results in terms.items %}
          <div class="student_report">
            <div class="report_college"><h2>KATHFORD INTERNATIONAL COLLEGE OF ENGINEERING AND MANAGEMENT</h2></div>
            <div class="report_term"><h2>{{ term }} Report Card</h2></div>
              <div class="student_info" xmlns="http://www.w3.org/1999/html">
                <h6>Name: {{ full_name }}</h6>
                <h6>Semester: {{ semester }}</h6>
                <h6>Course: {{ course }}</h6>
              </div>
          <div class="student_table">
            <table class="table table-bordered table-info">
            <thead class="thead-dark">
            <tr>
              <th>Subject</th>
              <th>Full Marks</th>
              <th>Pass Marks</th>
              <th>Obtained Marks</th>
            </tr>
            </thead>
              {% for item in results.marks %}
                  <tr>
                    {% for i in item %}
                        {% if item.2 > item.3 %}
                        <td class="table table-danger">{{ i }} </td>
                    {% else %}
                        <td>{{ i }}</td>
                    {% endif %}
                    {% endfor %}
                  </tr>
              {% endfor %}
            </table>
          </div>
            <div class="student_marks">
                <h6>Total: {{ results.total.marks }}</h6>
                <h6>Obtained: {{ results.total.obtained }}</h6>
                <h6>Percentage: {{ results.total.percentage|floatformat:'2' }} % </h6>
                <h6>Remarks:
                    {% for item in results.marks|slice:":1" %}
                        {% if item.2 > item.3 %}
                            Failed
                        {% else %}
                            <font color="#32cd32">Passed</font>
                        {% endif %}

                    {% endfor %}</h6>
            </div>
            <div class="student_chart">
                <a class="btn btn-secondary btn-sm" href="{% url 'Basics-chart-general' %}">Percentage Chart</a>
                <a class="btn btn-secondary btn-sm" href="{% url 'Basics-chart' %}"> Subject Chart</a>
            </div>
          <div class="report_verification">
              <h6>Verified By: Kathford</h6>
          </div>
          <div class="report_download">
              <a class="btn btn-secondary btn-sm" href="{% url 'pdf' term  %}"  > Download</a>
          </div>
          </div>

      {% endfor %}
    {% endfor %}


{% endblock %}